### PR TITLE
remove trailing semicolon

### PR DESCRIPTION
**Pull request by DanielRuf**
This also fixes the failing postcss-cssnext unit test.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Depends on https://github.com/MoOx/postcss-cssnext/pull/434

**Comment by jonathantneal** [comment]
How is this an improvement?

**Comment by DanielRuf** [comment]
This fixes the failing unit test of postcss and should be the default behavior. Without this the nesting test has the semicolon in the second rule.

Or is this a bug in the postcss-cssnext plugin?

**Comment by jonathantneal** [comment]
This change means that if a node explicitly has a trailing comma then it should not have a trailing comma. That does not make sense.

**Comment by DanielRuf** [comment]
See https://ci.appveyor.com/project/MoOx/postcss-cssnext/build/123/job/lw6fkcsw6gp4bq1w#L115

**Comment by DanielRuf** [comment]
Bump.

**Comment by jonathantneal** [comment]
I appreciate the bump, but I’m not sure why the test should not be updated. See my previous comment.

**Comment by DanielRuf** [comment]
It fixes the mentioned unit test and a trailing comma is not best practice in general.

**Comment by jonathantneal** [comment]
@DanielRuf, that is not a best practice recommended by the CSSWG. The test should be updated, and the tool should not be updated to explicitly do the opposite of what the code is saying.

**Comment by DanielRuf** [comment]
Ehm, postcss optimizes the code and trailing semicolons are not needed. See closure-stylesheets and other compressors and optimizers.

The generated code in other parts has no trailing semicolon, also when used with your plugin.

**Comment by jonathantneal** [comment]
@DanielRuf, I don’t intend to disregard your opinion, and I want to respect your persistence. Let me bring in @ai to help, if he’s available.

@ai, there is a very small change suggested here: https://github.com/jonathantneal/postcss-nesting/pull/51/files

It removes the trailing comma on any node, when that node is explicitly marked to have a semicolon. I’m against the change, but @DanielRuf indicates this is actually the expected behavior in PostCSS. This is not a best practice in plain CSS, but I don’t know about PostCSS. Do you care to chime in?

**Pull request closed without merging**
