### PR TITLE
Support direct nesting.

### LINKED ISSUE #10: Support direct nesting
Add support for the use of the `&` by itself (without `@nest` rule): http://tabatkins.github.io/specs/css-nesting/#direct-nesting

> nesting selector, written as an ASCII ampersand &.

> A style rule can be directly nested within another style rule if its selector is nest-prefixed.

### PR DESCRIPTION
**Pull request by tbremer**
This commit is to allows support for direct nesting per [the proposed spec](https://tabatkins.github.io/specs/css-nesting/)

In this commit I:
- add `walkRules` method
- update `ignore` tests for new methods
- add direct nesting test.

This should close #10

### CODE REVIEW

**Comment by tbremer** [comment]
I have a test setup for this type syntax:
```
a, b {
	color: white;
	@nest & c {
		color: blue;
		& d {
			color: orange
		}
	}
}

e, f {
	color: white;
	& g {
		color: blue;
		@nest & h {
			color: orange
		}
	}
}
```

The spec says 
>A style rule can have any number of nested style rules inside of it, of either type, intermixed with any number of declarations, in any order.

>The relative ordering of nested style rules and other declarations is important; it’s possible for a given style rule and a nested style rule within it to match the same element, and if the specificity of the two rules is otherwise equivalent, the relative order in the stylesheet of the applicable declarations determines which declaration "wins" the cascade.

I wasn't sure if determining specificity was something we should put into this, so I left the test out.

**Comment by MichielBijl** [comment]
+1

**Comment by rofrol** [comment]
Please merge it

**Comment by MichalZalecki** [comment]
+1

**Comment by morishitter** [comment]
+1

**Comment by MeoMix** [comment]
Hello?? Merge it? Or I'll fork the repo and maintain this if you've abandoned it?

**Comment by MoOx** [comment]
@jonathantneal is there any problem with this PR? If so explain.

**Comment by rofrol** [comment]
What about updating https://www.npmjs.com/package/postcss-nesting ?

**Comment by jonathantneal** [comment]
Once I have some spare time, I want https://github.com/jonathantneal/postcss-nesting/blob/master/index.js#L23 and https://github.com/jonathantneal/postcss-nesting/blob/master/index.js#L62 to be grouped together.

**Comment by jonathanKingston** [comment]
@jonathantneal could you bump the release of this in npm please?
Thanks

**Comment by jonathantneal** [comment]
Unfortunately, this pull added support for invalid nesting, so I cannot. For instance:

```css
c & {
	color: blue;
}
```

Should not be transformed.  I am looking into this.

**Comment by jonathantneal** [comment]
All right, this is now resolved by https://github.com/jonathantneal/postcss-nesting/commit/658b8b7e5b76c49a4d7752f3136247a2173b5b7a and has been updated on npm.

**Comment by MichielBijl** [comment]
Nice work. Thank you @jonathantneal

**Comment by rofrol** [comment]
:+1:

**Pull request merged**
